[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'aklt/plantuml-syntax'
